### PR TITLE
Replace deprecated usage of Promise.defer

### LINKED ISSUE #52: TypeError: Promise.defer is not a function
When using Node.js V7.0 and calling `.produce`, I get the following error:

```
bmq:producer TypeError: Promise.defer is not a function
    at createRpcQueue.call.then (C:\project\node_modules\bunnymq\src\modules\producer.js:121:43)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### PR DESCRIPTION
**Pull request by PuKoren**
Fixes #52

### CODE REVIEW

File: src/modules/producer.js [hunk 1]
```diff
@@ -118,7 +119,7 @@ function checkRpc (queue, msg, options) {
 
         if (publishOrSendToQueue.call(this, queue, msg, options)) {
             //defered promise that will resolve when response is received
-            let responsePromise = Promise.defer();
+            let responsePromise =  new Deferred();
```
Comment (mrister) [inline src/modules/producer.js:122]: I don't think we need another class just for this, and an Es6 one at that (we use var all over the place and have no engine requirement in package.json that would signal we need es6 support). Can't we just use a Promise or do that what you did here in an es5 way?

**Review by mrister — CHANGES_REQUESTED** [review]

File: src/modules/producer.js (hunk 1 above)
Comment (PuKoren) [reply src/modules/producer.js:122]: We support only es6 for now, see there: https://github.com/dial-once/node-bunnymq#installation
Because we use `let`, `() =>` etc.

And this is not an es6 class, it is es5 compliant homemade class (bundled in the PR). If you have another idea to fullfil a promise outside of its own scope, would be glad to replace it!

We had to remove its usage because it has been removed from node7, see #52

Comment (mrister) [reply src/modules/producer.js:122]: Oh you are right however we need to then set engine entry in package.js to make sure npm install does not work on node < 6.  On that Promise.deffer note here is a good discussion http://stackoverflow.com/questions/34971078/how-to-replace-promise-defer-with-new-promise

I think we need to refactor this piece of code return promises where needed instead of using deferred.

Comment (PuKoren) [reply src/modules/producer.js:122]: Thing is, how do you replace it? Just using `new Promise` does not help because it should be resolved outside of the scope:

``` js
function resolveIt(promise) {
  promise.resolve();
}

//when launching a RPC message
const myPromise = new Promise();
myPromise.then(function() {
  console.log('Someone resolved me! Hourra!');
});


//somewhere else, when RPC message response is received
resolveIt(myPromise);
```

About package.json nodejs version: https://github.com/dial-once/node-bunnymq/pull/56

Comment (mrister) [reply src/modules/producer.js:122]: OK I understand if this is a quick fix then it is fine there is no simple replacement so yours is ok. however this whole thing should be refactored to not use a defer mechanism if possible (i did not go through the code in detail to know exactly which way to do it now)  at all. It is a little bigger refactor for sure.

**Review by ykhatal — APPROVED** [review]

File: src/modules/producer.js (hunk 1 above)
Comment (mrister) [reply src/modules/producer.js:122]: @PuKoren If you want to go ahead for a release with this to be compatible with Node v7 then i will approve and I will create a task for refactor.

Comment (PuKoren) [reply src/modules/producer.js:122]: Sure, it would take too long otherwise

For the refactor, you can also mention that the whole project needs a proper refactor using es6 syntax more globally - with classes, await, etc. and removal of the usage of arrow functions and `this` everywhere - it's a real mess!

Comment (mrister) [reply src/modules/producer.js:122]: OK then.

**Review by mrister — APPROVED** [review]

**Review by jkernech — APPROVED** [review]
